### ISSUE TITLE
Unexpected Energy Transfer

### ISSUE THREAD

**Issue by FallenEagle1** [CyclopsMC/IntegratedTunnels#156]
#### Issue type:

- :bug: Bug

____

#### Short description:

When looking further into #148 and CyclopsMC/IntegratedDynamics#696, I came across some interesting interactions, and curious if this may relate to those at all. Basically, energy transfer dealing with omni-directional connectors seems to be coordinate bound. 

#### Steps to reproduce the problem:
![image](https://user-images.githubusercontent.com/22630113/52922022-a2f90980-32da-11e9-939c-bae0cc93893b.png)
Premise is this: All of the enderio capacitor banks are set so that they can input and output rf from the same side, and they are connected to ID through energy interfaces. Each of them have their own omnidirectional connector that are on the same group (group 27, but not thinking number matters too much) The capacitors and the trash cans with the red dots have an omniconnector that is group 36. In this case, the capacitors have both a group 27 and 36 omniconnector on them, so everything is technically connected. For reference, North (negative Z) it in the opposite direction of which the picture was taken, so negative X is out the right side of the picture.

The steps below are not exactly the order I found these out, more of just a somewhat straightforward way to test.

First thing done was fill all of the capacitors with the creative rf source. Only a couple would fill at a time, but the first issue noticed was that while filling, the rf input limit on the capacitors was ignored. They would fill at 100,000 rf/t, and the cap banks are supposed to be limited to 25,000 rf/t.

Next thing done was to drain the capacitor banks.

![image](https://user-images.githubusercontent.com/22630113/52922703-59132200-32e0-11e9-8a8f-7b70befd2a06.png)

From what was found, when the energy trash can on the far left was connected, none of the capacitor banks were drained. When the red or blue circled trashcan was connected, from the corresponding colored line and left (positive X) where drained. Far right allowed for all of the capacitor banks to drain. So it seems like that the connectors are bound in the x direction, but not the z direction, provided that everything is connected with interfaces.

To round out the testing, I tried using exports and imports on the trashcans and the creative rf source. The import worked just fine, except for the input limit ignoring, but none of the exports worked at all.

I'm wondering if these coordinate issues would be tied to the slotless source issue referenced above. Might just be a wild guess, but at the very least they are bugs on their own accord.

#### List of issues noticed:
Input limit ignored
Interfaces seem to be coordinate bound when dealing with omni-directional connectors
Export energy doesn't seem to work through omni's at all.

#### Versions:

- Integrated Dynamics: 1.0.3 and 1.0.6
- Integrated Tunnels: 1.6.2 and 1.6.6
- Cyclops Core: 1.0.2 and 1.0.4
- Minecraft: 1.12.2
- Forge: 14.23.5.2811
Done on ATM 3 Remix 1.0.3

**Comment by rubensworks** [comment]
So, a couple of things:

> Input limit ignored

Limits must be enforced on the energy storage, so this sounds like an EIO issue.

> Interfaces seem to be coordinate bound when dealing with omni-directional connectors

That's correct. In fact, _all_ ID logic happens in a certain order, which is defined by coordinates.

> Export energy doesn't seem to work through omni's at all

Are you sure this happens only with omni-connectors? I've heard of issues before with EIO capacitors because they may doing some strange things with their energy storage interface. What happens if you replace these capacitors with for example an ID energy battery?

**Comment by FallenEagle1** [comment]
Sorry, got sidetracked by things. Input, I'll look into getting an issue open with Eio, will do some more testing for that then, to see if the capacitor banks exhibit this with other mods. As far as I was aware, ID/IT was the only mod it seems to be happening with, so thought it was something with these. It seems like a different I can't even get the input issue to replicate, so not sure what was up with that.

As for the coordinate part, I almost expected the calcs to be based on that, I just didn't expect that whether or not the omni directional works at all to be somewhat bound by the coordinates. From the testing above, all of the exports should have been working on all of the capacitors, not just the ones that were on one side or the other of the omni directional that the export was attached to. It seems like a number of the bugs are attached to the fact that the capacitor banks allow for both input and output of the same face at the same time, instead of just one or the other.

**Comment by rubensworks** [comment]
@FallenEagle1 I'm sorry, but this problem is still not fully clear to me. Could you provide a reproducible case (a world save would be great) where this error occurs with just Cyclops mods loaded?

(Honestly, I've been putting this issue off a bit due to the walls of texts, so it would be great if you could make your future comments a bit shorter and to the point :-) )
