### ISSUE TITLE
Player Simulator dupe bugs

### ISSUE THREAD

**Issue by RoarkCats** [CyclopsMC/IntegratedTunnels#339]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Certain items function abnormally in player simulators, causing dupe bugs and other weird occurances

As these sorts of bugs can be like whack-a-mole, I would suggest a mod config blacklist for pack devs to globally disable specific broken items with the player simulator, but here are two if they might help improve its implementation

#### Steps to reproduce the problem:

1. Setup a player simulator connected to a storage
2. Set the simulator to click an item in the storage
   a. Illuminati Pet (Inventory Pets, usable no cooldown or durability)
   b. Glass Bottle on Lava (Alex's Mobs, drops Lava Bottle without consuming bottle)

#### Expected behaviour:

a. Illuminati Pet should go on cooldown and run out of durability (it does with Create's Deployer)
b. Lava Bottle should consume or replace the Glass Bottle

![Image](https://github.com/user-attachments/assets/83b39fbd-8959-4dea-9fca-b40466129829)
(my lava bottle farm dupe setup)
____

#### Versions:

- This mod: 1.8.39
- Minecraft: 1.20.1
- Mod loader version: Forge 47.4.0

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by Jack-McKalling** [comment]
What is your Integrated Dynamics version?

**Comment by rubensworks** [comment]
The Glass Bottle on Lava should be fixed in next release.

I couldn't easily test the Illuminati Pet. Should it still be an issue on your end, please let me know. Might also be related to https://github.com/CyclopsMC/IntegratedTunnels/issues/281

**Comment by RoarkCats** [comment]
1.27.1 is my ID base mod version btw

**Comment by Jack-McKalling** [comment]
Then I suggest to update all Integrated mods, the above fixes should at least solve one of the two cases.
On top of that, you won't be using an outdated version anymore since there have been newer releases after your current.

**Comment by RoarkCats** [comment]
Confirmed Lava Bottles fixed,
Inventory Pet still broken

<img src="https://github.com/user-attachments/assets/504fddd9-c735-478d-af02-0bf622c0217e" width=50%>

Reproduction notes:
- The nbt of the illuminati pet item in the item variable may need to match the actual one (easily accomplished or disabled?) 
- If the pet is already on cooldown it will need the 60s to go off cooldown even in the simulator, but then it will give infinite items for free no cooldown

<img src="https://github.com/user-attachments/assets/cca9dc05-49a2-4ea8-bf9e-7ce27cc76026" width=50%>

**Comment by rubensworks** [comment]
@RoarkCats Could you share a short video or something similar that allows me to see the steps to reproduce the problem? (I don't know the Inventory Pets mod atm)

**Comment by RoarkCats** [comment]
Sure, here I explain the full functionality of the pet, the dupe, and give two counter examples of other mods where its not bugged

[Integrated Dynamics Inventory Pets Dupe Bug Demo](https://youtu.be/5cp7mTWIMgA)
[![Video Thumbnail](http://img.youtube.com/vi/5cp7mTWIMgA/0.jpg)](http://www.youtube.com/watch?v=5cp7mTWIMgA "Integrated Dynamics Inventory Pets Dupe Bug Demo")

**Comment by rubensworks** [comment]
Thanks! I'll try to look into it soon.
